export const RESEARCHFIELDS = {
  'Agriculture and Forestry': [
    'Agricultural Economics & Policy',
    'Agricultural Engineering',
    'Agriculture, Dairy & Animal Science',
    'Agriculture, Multidisciplinary',
    'Agronomy',
    'Anatomy & Morphology',
    'Behavioral Sciences',
    'Biochemistry & Molecular Biology',
    'Biology',
    'Biotechnology & Applied Microbiology',
    'Chemistry, Analytical',
    'Chemistry, Applied',
    'Dermatology',
    'Ecology',
    'Education, Scientific Disciplines',
    'Engineering, Chemical',
    'Entomology',
    'Environmental Sciences',
    'Fisheries',
    'Food Science & Technology',
    'Forestry',
    'Genetics & Heredity',
    'Geosciences, Multidisciplinary',
    'Horticulture',
    'Immunology',
    'Infectious Diseases',
    'Microbiology',
    'Nutrition & Dietetics',
    'Parasitology',
    'Pathology',
    'Pharmacology & Pharmacy',
    'Plant Sciences',
    'Reproductive Biology',
    'Soil Science',
    'Veterinary Sciences',
    'Zoology'
  ],
  Biology: [
    'Agriculture, Dairy & Animal Science',
    'Agronomy',
    'Anatomy & Morphology',
    'Astronomy & Astrophysics',
    'Behavioral Sciences',
    'Biochemical Research Methods',
    'Biochemistry & Molecular Biology',
    'Biodiversity Conservation',
    'Biology',
    'Biophysics',
    'Biotechnology & Applied Microbiology',
    'Cell Biology',
    'Chemistry, Applied',
    'Chemistry, Medicinal',
    'Developmental Biology',
    'Ecology',
    'Endocrinology & Metabolism',
    'Entomology',
    'Environmental Sciences',
    'Evolutionary Biology',
    'Fisheries',
    'Forestry',
    'Genetics & Heredity',
    'Immunology',
    'Marine & Freshwater Biology',
    'Mathematical & Computational Biology',
    'Microbiology',
    'Multidisciplinary Sciences',
    'Mycology',
    'Neurosciences',
    'Ornithology',
    'Parasitology',
    'Physiology',
    'Plant Sciences',
    'Reproductive Biology',
    'Veterinary Sciences',
    'Zoology'
  ],
  Chemistry: [
    'Acoustics',
    'Automation & Control Systems',
    'Biochemical Research Methods',
    'Biochemistry & Molecular Biology',
    'Chemistry, Analytical',
    'Chemistry, Applied',
    'Chemistry, Inorganic & Nuclear',
    'Chemistry, Medicinal',
    'Chemistry, Multidisciplinary',
    'Chemistry, Organic',
    'Chemistry, Physical',
    'Crystallography',
    'Electrochemistry',
    'History & Philosophy Of Science',
    'Instruments & Instrumentation',
    'Pharmacology & Pharmacy',
    'Physics, Atomic, Molecular & Chemical',
    'Polymer Science',
    'Spectroscopy'
  ],
  'Computer Science': [
    'Acoustics',
    'Astronomy & Astrophysics',
    'Automation & Control Systems',
    'Biochemical Research Methods',
    'Biology',
    'Cell Biology',
    'Computer Science, Artificial Intelligence',
    'Computer Science, Cybernetics',
    'Computer Science, Hardware & Architecture',
    'Computer Science, Information Systems',
    'Computer Science, Interdisciplinary Applications',
    'Computer Science, Software Engineering',
    'Computer Science, Theory & Methods',
    'Ecology',
    'Engineering, Aerospace',
    'Engineering, Biomedical',
    'Engineering, Electrical & Electronic',
    'Engineering, Industrial',
    'Engineering, Mechanical',
    'Engineering, Multidisciplinary',
    'Evolutionary Biology',
    'Imaging Science & Photographic Technology',
    'Logic',
    'Mathematical & Computational Biology',
    'Mathematics',
    'Mathematics, Interdisciplinary Applications',
    'Robotics',
    'Statistics & Probability',
    'Telecommunications'
  ],
  'Ecology and Environmental Science': [
    'Agriculture, Multidisciplinary',
    'Behavioral Sciences',
    'Biochemistry & Molecular Biology',
    'Biodiversity Conservation',
    'Biology',
    'Biotechnology & Applied Microbiology',
    'Chemistry, Analytical',
    'Chemistry, Inorganic & Nuclear',
    'Chemistry, Multidisciplinary',
    'Computer Science, Interdisciplinary Applications',
    'Construction & Building Technology',
    'Ecology',
    'Energy & Fuels',
    'Engineering, Chemical',
    'Engineering, Civil',
    'Engineering, Environmental',
    'Environmental Sciences',
    'Fisheries',
    'Forestry',
    'Geology',
    'Green & Sustainable Science & Technology',
    'Limnology',
    'Marine & Freshwater Biology',
    'Meteorology & Atmospheric Sciences',
    'Oceanography',
    'Plant Sciences',
    'Water Resources'
  ],
  Economics: [
    'Agricultural Economics & Policy',
    'Ecology',
    'Energy & Fuels',
    'Engineering, Industrial',
    'Fisheries',
    'Health Care Sciences & Services',
    'Mathematics, Interdisciplinary Applications',
    'Operations Research & Management Science',
    'Statistics & Probability'
  ],
  Engineering: [
    'Acoustics',
    'Agricultural Engineering',
    'Agronomy',
    'Anatomy & Morphology',
    'Automation & Control Systems',
    'Biochemical Research Methods',
    'Biochemistry & Molecular Biology',
    'Biology',
    'Biophysics',
    'Biotechnology & Applied Microbiology',
    'Cardiac & Cardiovascular Systems',
    'Cell & Tissue Engineering',
    'Cell Biology',
    'Chemistry, Analytical',
    'Chemistry, Applied',
    'Chemistry, Inorganic & Nuclear',
    'Chemistry, Multidisciplinary',
    'Chemistry, Organic',
    'Chemistry, Physical',
    'Computer Science, Artificial Intelligence',
    'Computer Science, Cybernetics',
    'Computer Science, Hardware & Architecture',
    'Computer Science, Information Systems',
    'Computer Science, Interdisciplinary Applications',
    'Computer Science, Software Engineering',
    'Computer Science, Theory & Methods',
    'Construction & Building Technology',
    'Dentistry, Oral Surgery & Medicine',
    'Education, Scientific Disciplines',
    'Electrochemistry',
    'Energy & Fuels',
    'Engineering, Aerospace',
    'Engineering, Biomedical',
    'Engineering, Chemical',
    'Engineering, Civil',
    'Engineering, Electrical & Electronic',
    'Engineering, Environmental',
    'Engineering, Geological',
    'Engineering, Industrial',
    'Engineering, Manufacturing',
    'Engineering, Marine',
    'Engineering, Mechanical',
    'Engineering, Multidisciplinary',
    'Engineering, Ocean',
    'Engineering, Petroleum',
    'Environmental Sciences',
    'Food Science & Technology',
    'Geography, Physical',
    'Geosciences, Multidisciplinary',
    'History & Philosophy Of Science',
    'Imaging Science & Photographic Technology',
    'Instruments & Instrumentation',
    'Materials Science, Biomaterials',
    'Materials Science, Characterization & Testing',
    'Materials Science, Composites',
    'Materials Science, Multidisciplinary',
    'Mathematical & Computational Biology',
    'Mathematics, Applied',
    'Mathematics, Interdisciplinary Applications',
    'Mechanics',
    'Medicine, Research & Experimental',
    'Metallurgy & Metallurgical Engineering',
    'Microscopy',
    'Mineralogy',
    'Mining & Mineral Processing',
    'Multidisciplinary Sciences',
    'Nanoscience & Nanotechnology',
    'Neurosciences',
    'Nuclear Science & Technology',
    'Operations Research & Management Science',
    'Optics',
    'Pharmacology & Pharmacy',
    'Physics, Applied',
    'Polymer Science',
    'Radiology, Nuclear Medicine & Medical Imaging',
    'Remote Sensing',
    'Statistics & Probability',
    'Thermodynamics',
    'Transportation Science & Technology'
  ],
  Geoscience: [
    'Astronomy & Astrophysics',
    'Biodiversity Conservation',
    'Biology',
    'Biophysics',
    'Chemistry, Analytical',
    'Chemistry, Multidisciplinary',
    'Chemistry, Physical',
    'Computer Science, Information Systems',
    'Computer Science, Interdisciplinary Applications',
    'Ecology',
    'Energy & Fuels',
    'Engineering, Civil',
    'Engineering, Environmental',
    'Engineering, Geological',
    'Engineering, Ocean',
    'Environmental Sciences',
    'Evolutionary Biology',
    'Geochemistry & Geophysics',
    'Geography, Physical',
    'Geology',
    'Geosciences, Multidisciplinary',
    'Imaging Science & Photographic Technology',
    'Limnology',
    'Marine & Freshwater Biology',
    'Materials Science, Multidisciplinary',
    'Meteorology & Atmospheric Sciences',
    'Mineralogy',
    'Oceanography',
    'Paleontology',
    'Remote Sensing',
    'Water Resources'
  ],
  Humanities: [
    'Acoustics',
    'Agriculture, Multidisciplinary',
    'Audiology & Speech-language Pathology',
    'Biodiversity Conservation',
    'Biology',
    'Chemistry, Multidisciplinary',
    'Computer Science, Theory & Methods',
    'Engineering, Multidisciplinary',
    'Geosciences, Multidisciplinary',
    'Health Care Sciences & Services',
    'History & Philosophy Of Science',
    'Mathematics',
    'Medical Ethics'
  ],
  Law: [
    'Agriculture, Multidisciplinary',
    'Biology',
    'Computer Science, Interdisciplinary Applications',
    'Ecology',
    'Environmental Sciences',
    'Evolutionary Biology',
    'Geography, Physical',
    'History & Philosophy Of Science',
    'Mathematics, Interdisciplinary Applications'
  ],
  Management: [
    'Computer Science, Cybernetics',
    'Computer Science, Information Systems',
    'Computer Science, Interdisciplinary Applications',
    'Computer Science, Software Engineering',
    'Engineering, Industrial',
    'Engineering, Manufacturing',
    'Engineering, Multidisciplinary',
    'Operations Research & Management Science',
    'Sport Sciences',
    'Telecommunications'
  ],
  'Material Science': [
    'Biotechnology & Applied Microbiology',
    'Chemistry, Applied',
    'Chemistry, Multidisciplinary',
    'Chemistry, Physical',
    'Crystallography',
    'Electrochemistry',
    'Energy & Fuels',
    'Engineering, Biomedical',
    'Engineering, Chemical',
    'Engineering, Electrical & Electronic',
    'Engineering, Industrial',
    'Engineering, Manufacturing',
    'Engineering, Mechanical',
    'Forestry',
    'Green & Sustainable Science & Technology',
    'Instruments & Instrumentation',
    'Materials Science, Ceramics',
    'Materials Science, Characterization & Testing',
    'Materials Science, Coatings & Films',
    'Materials Science, Composites',
    'Materials Science, Multidisciplinary',
    'Materials Science, Paper & Wood',
    'Materials Science, Textiles',
    'Metallurgy & Metallurgical Engineering',
    'Mineralogy',
    'Polymer Science'
  ],
  Mathematics: [
    'Automation & Control Systems',
    'Biochemistry & Molecular Biology',
    'Biology',
    'Chemistry, Physical',
    'Computer Science, Interdisciplinary Applications',
    'Computer Science, Software Engineering',
    'Computer Science, Theory & Methods',
    'Engineering, Multidisciplinary',
    'Logic',
    'Mathematical & Computational Biology',
    'Mathematics',
    'Mathematics, Applied',
    'Mathematics, Interdisciplinary Applications',
    'Operations Research & Management Science',
    'Physics, Mathematical',
    'Statistics & Probability'
  ],
  Medicine: [
    'Acoustics',
    'Allergy',
    'Anatomy & Morphology',
    'Andrology',
    'Anesthesiology',
    'Audiology & Speech-language Pathology',
    'Behavioral Sciences',
    'Biochemical Research Methods',
    'Biochemistry & Molecular Biology',
    'Biodiversity Conservation',
    'Biology',
    'Biophysics',
    'Biotechnology & Applied Microbiology',
    'Cardiac & Cardiovascular Systems',
    'Cell & Tissue Engineering',
    'Cell Biology',
    'Chemistry, Analytical',
    'Chemistry, Applied',
    'Chemistry, Medicinal',
    'Chemistry, Multidisciplinary',
    'Chemistry, Physical',
    'Clinical Neurology',
    'Computer Science, Information Systems',
    'Computer Science, Interdisciplinary Applications',
    'Critical Care Medicine',
    'Dentistry, Oral Surgery & Medicine',
    'Dermatology',
    'Developmental Biology',
    'Ecology',
    'Education, Scientific Disciplines',
    'Emergency Medicine',
    'Endocrinology & Metabolism',
    'Environmental Sciences',
    'Evolutionary Biology',
    'Food Science & Technology',
    'Gastroenterology & Hepatology',
    'Genetics & Heredity',
    'Geriatrics & Gerontology',
    'Health Care Sciences & Services',
    'Hematology',
    'History & Philosophy Of Science',
    'Immunology',
    'Infectious Diseases',
    'Instruments & Instrumentation',
    'Integrative & Complementary Medicine',
    'Marine & Freshwater Biology',
    'Mathematical & Computational Biology',
    'Mathematics, Interdisciplinary Applications',
    'Medical Ethics',
    'Medical Informatics',
    'Medical Laboratory Technology',
    'Medicine, General & Internal',
    'Medicine, Legal',
    'Medicine, Research & Experimental',
    'Microbiology',
    'Mycology',
    'Nanoscience & Nanotechnology',
    'Neuroimaging',
    'Neurosciences',
    'Nursing',
    'Nutrition & Dietetics',
    'Obstetrics & Gynecology',
    'Oncology',
    'Ophthalmology',
    'Optics',
    'Orthopedics',
    'Otorhinolaryngology',
    'Parasitology',
    'Pathology',
    'Pediatrics',
    'Peripheral Vascular Disease',
    'Pharmacology & Pharmacy',
    'Physiology',
    'Primary Health Care',
    'Psychiatry',
    'Psychology',
    'Public, Environmental & Occupational Health',
    'Radiology, Nuclear Medicine & Medical Imaging',
    'Rehabilitation',
    'Reproductive Biology',
    'Respiratory System',
    'Rheumatology',
    'Sport Sciences',
    'Substance Abuse',
    'Surgery',
    'Toxicology',
    'Transplantation',
    'Tropical Medicine',
    'Urology & Nephrology',
    'Veterinary Sciences',
    'Virology'
  ],
  'Multidisciplinary Journals': [
    'Chemistry, Analytical',
    'Ecology',
    'History & Philosophy Of Science',
    'Mathematical & Computational Biology',
    'Mathematics, Interdisciplinary Applications',
    'Multidisciplinary Sciences'
  ],
  Pedagogy: [
    'Biochemistry & Molecular Biology',
    'Biology',
    'Computer Science, Interdisciplinary Applications',
    'Dentistry, Oral Surgery & Medicine',
    'Education, Scientific Disciplines',
    'History & Philosophy Of Science',
    'Sport Sciences'
  ],
  'Physics and Astrophysics': [
    'Acoustics',
    'Astronomy & Astrophysics',
    'Biochemical Research Methods',
    'Biology',
    'Chemistry, Inorganic & Nuclear',
    'Chemistry, Physical',
    'Computer Science, Interdisciplinary Applications',
    'Computer Science, Theory & Methods',
    'Education, Scientific Disciplines',
    'Engineering, Electrical & Electronic',
    'History & Philosophy Of Science',
    'Instruments & Instrumentation',
    'Materials Science, Multidisciplinary',
    'Mathematics, Applied',
    'Mathematics, Interdisciplinary Applications',
    'Mechanics',
    'Nanoscience & Nanotechnology',
    'Nuclear Science & Technology',
    'Optics',
    'Physics, Applied',
    'Physics, Atomic, Molecular & Chemical',
    'Physics, Condensed Matter',
    'Physics, Fluids & Plasmas',
    'Physics, Mathematical',
    'Physics, Multidisciplinary',
    'Physics, Nuclear',
    'Physics, Particles & Fields',
    'Spectroscopy'
  ],
  Psychology: [
    'Audiology & Speech-language Pathology',
    'Behavioral Sciences',
    'Biophysics',
    'Clinical Neurology',
    'Computer Science, Artificial Intelligence',
    'Developmental Biology',
    'Mathematics, Interdisciplinary Applications',
    'Multidisciplinary Sciences',
    'Neurosciences',
    'Ophthalmology',
    'Physiology',
    'Psychology'
  ]
};
