export const ROUTES = {
  signIn: '/signIn',
  signUp: '/signUp',
  profile: '/profile',
  resetPassword: '/resetPassword',
  home: '/home',
  explore: '/explore',
  root: '/',
  favorites: '/favorites',
  comments: '/comments',
  webinars: '/webinars',
  peerReviews: '/peerReviews',
  hubs: '/hubs',
  publications: '/publications',
  editProfile: '/editProfile',
  authors: '/authors',
  journals: '/journals',
  settings: '/settings',
  notFound: '*',
  onboarding: '/onboarding',
  pinned: '/pinned',
  changePassword: '/changePassword',
  changeEmail: '/changeEmail',
  chat: '/chat'
};
